// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.




#include "Claw.h"
#include "../RobotMap.h"
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

Claw::Claw() : Subsystem("Claw") {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	heightEncoder = RobotMap::clawHeightEncoder;
	clawMotor = RobotMap::clawClawMotor;
	level0 = RobotMap::clawLevel0;
	level1 = RobotMap::clawLevel1;
	level2 = RobotMap::clawLevel2;
	level3 = RobotMap::clawLevel3;
	level4 = RobotMap::clawLevel4;
	level5 = RobotMap::clawLevel5;
	level6 = RobotMap::clawLevel6;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

	for(int i = 0; i < sizeof(level); i++) {
		level[0] = false;
	}
}
    
void Claw::InitDefaultCommand() {
	// Set the default command for a subsystem here.
	//SetDefaultCommand(new MySpecialCommand());
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
}


// Put methods for controlling this subsystem
// here. Call these from Commands.

void Claw::SetMotor(float velocity) {
	clawMotor->Set(velocity);
}

double Claw::GetHeight() {
	return heightEncoder->GetRaw();
}

bool Claw::GetLevel(int levelNumber) {
	return level[levelNumber];
}




