// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.




#include "ContainerWinch.h"
#include "../RobotMap.h"
#include "../Commands/WinchControl.h"
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

ContainerWinch::ContainerWinch() : Subsystem("ContainerWinch") {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	containerPull1 = RobotMap::containerWinchContainerPull1;
	containerPull2 = RobotMap::containerWinchContainerPull2;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
}
    
void ContainerWinch::InitDefaultCommand() {
	// Set the default command for a subsystem here.
	SetDefaultCommand(new WinchControl);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
}


// Put methods for controlling this subsystem
// here. Call these from Commands.


void ContainerWinch::SetWinch(int winchNumber, float output) {
	switch (winchNumber) {
		case 1:
			containerPull1->Set(output);
			break;
		case 2:
			containerPull2->Set(output);
			break;
		default:
			containerPull1->Set(0);
			containerPull2->Set(0);
			break;
	}
}
