// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef DRIVETRAIN_H
#define DRIVETRAIN_H
#include "Commands/Subsystem.h"
#include <WPILib.h>
#include <CANTalon.h>

/**
 *
 *
 * @author ExampleAuthor
 */
class Drivetrain: public Subsystem {
private:
	// It's desirable that everything possible under private except
	// for methods that implement subsystem capabilities
public:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	Encoder* rearRight;
	Encoder* rearLeft;
	Encoder* frontLeft;
	Encoder* frontRight;
	Gyro* gyro1;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	CANTalon* speedController2;
	CANTalon* speedController1;
	CANTalon* speedController3;
	CANTalon* speedController4;
	RobotDrive* robotDrive;

	Drivetrain();
	void InitDefaultCommand();

	void Go(float magnitude, float angle);
	float GetGyro();

};

#endif
