// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.




#include "LEDindicator.h"
#include "../RobotMap.h"
#include "../Robot.h"


LEDindicator::LEDindicator() : Subsystem("LEDindicator") {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
}
    
void LEDindicator::InitDefaultCommand() {
	// Set the default command for a subsystem here.
	//SetDefaultCommand(new MySpecialCommand());
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
}

void LEDindicator::TurnLEDon() {
	Robot::oi->getJoystick3()->SetOutput(1, true);
}

void LEDindicator::TurnLEDoff() {
	Robot::oi->getJoystick3()->SetOutput(1, false);
}

// Put methods for controlling this subsystem
// here. Call these from Commands.

