// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "Place.h"

Place::Place() {
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::clawPID);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}

// Called just before this Command runs the first time
void Place::Initialize() {
	Robot::clawPID->Enable();
//	if (Robot::clawPID->GetSetpoint() >= Robot::clawPID->PLACEOFFSET + Robot::clawPID->MINSETPOINT) {
//		Robot::clawPID->SetSetpoint(Robot::clawPID->GetSetpoint() - Robot::clawPID->PLACEOFFSET);
//	}
	Robot::clawPID->SetSetpointRelative(Robot::clawPID->PLACEOFFSET);
}

// Called repeatedly when this Command is scheduled to run
void Place::Execute() {
	
}

// Make this return true when this Command no longer needs to run execute()
bool Place::IsFinished() {
	return Robot::clawPID->OnTarget();
}

// Called once after isFinished returns true
void Place::End() {
	Robot::clawPID->Disable();
}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void Place::Interrupted() {
	Robot::clawPID->Disable();
}
