// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef OI_H
#define OI_H

#include "WPILib.h"
#include "Controller/TriggerButton.h"

class OI {
private:

	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	Joystick* joystick3;
	Joystick* joystick2;
	Joystick* joystick1;

	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

	// Joytick button constants
	const int resetButtonNum = 3;
	const int pickUpNum = 1;
	const int dropContainersNum = 8;
	const int centerNum = 6;
	const int rightInNum = 4;
	const int rightOutNum = 6;
	const int leftInNum = 3;
	const int leftOutNum = 5;
	const int stationPickUpNum = 1;
	const int feederHeightNum = 16;

	const int clawOverideNum = 1;

	const int intakeNum = 3;
	const int outakeNum = 2;

	const int level1Num = 3;
	const int level2Num = 5;
	const int level3Num = 4;
	const int level4Num = 8;
	const int level5Num = 6;
	const int level6Num = 2;
	const int level7Num = 7;
	const int placeButtonNum = 14;
	const int coopLevelNum = 15;


	//	 JoystickButton* tempLevel1;
	JoystickButton* resetButton;
	JoystickButton* pickUp;
	JoystickButton* dropContainers;
	JoystickButton* center;
	//	 JoystickButton* secondaryPlace;
	JoystickButton* rightIn;
	JoystickButton* rightOut;
	JoystickButton* leftIn;
	JoystickButton* leftOut;
	JoystickButton* stationPickUp;
	JoystickButton* feederHeight;

	TriggerButton* clawOveridePos;
	TriggerButton* clawOverideNeg;

	TriggerButton* intake;
	TriggerButton* outake;

	JoystickButton* level1;
	JoystickButton* level2;
	JoystickButton* level3;
	JoystickButton* level4;
	JoystickButton* level5;
	JoystickButton* level6;
	JoystickButton* level7;
	JoystickButton* placeButton;
	JoystickButton* coopLevel;

public:
	 bool desensitize;

	OI();
 
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PROTOTYPES

	Joystick* getJoystick1();
	Joystick* getJoystick2();
	Joystick* getJoystick3();

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PROTOTYPES
	float GetX();
	float GetY();
	float GetR();
	float GetClawOveride();
	float Desensitize(int axisNumber, float threshold, float dsdivision);
	float GetJoystick2POV();
};

#endif
